---
- name: Httpd
  hosts: all
  gather_facts: False
  tasks:
  - name: httpd install
    yum:
      name: httpd
      state: Present

- name: httpd restart
  service:
    name: httpd
    state: started
  
    

